apiVersion: v2
name: one37id-ibm-agent
type: application
description: A Helm chart to deploy the One37 Business Connector Agent
home: https://one37id.com
icon: https://www.one37id.com/images/connector.svg
annotations:
  category: Infrastructure
  licenses: Apache-2.0
dependencies:
  - name: one37secrets
    repository: file://../one37secrets
    tags:
    - one37secrets
    version: 1.2310.10-2
keywords:
  - businessconnector
  - ssi
  - aries
  - agent
  - one37id
  - one37
  - one37id.com
maintainers:
  - name: One37 Solutions, Inc.
    url: https://github.com/one37id/charts
appVersion: "1.2310.13-3"
version: 1.2310.13-3
