{{- if .Values.secrets.create }}
{{- $fullName := include "one37id-ibm-agent-db.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName | quote  }}
  namespace: {{ .Release.Namespace | quote  }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.app }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}